"""Initial schema

Revision ID: 0082d55b2e58
Revises: 
Create Date: 2026-03-29 23:45:52.505615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0082d55b2e58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('model_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_sources_user_id'), 'model_sources', ['user_id'], unique=False)
    op.create_table('model_source_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('context_window_tokens', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['model_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_source_models_source_id'), 'model_source_models', ['source_id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=False),
    sa.Column('merge_parent_id', sa.String(length=36), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merge_parent_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_chat_id'), 'nodes', ['chat_id'], unique=False)
    op.create_index(op.f('ix_nodes_merge_parent_id'), 'nodes', ['merge_parent_id'], unique=False)
    op.create_index(op.f('ix_nodes_parent_id'), 'nodes', ['parent_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_node_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['head_node_id'], ['nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'name', name='uq_branch_chat_name')
    )
    op.create_index(op.f('ix_branches_chat_id'), 'branches', ['chat_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('default_model_id', sa.String(length=36), nullable=True),
    sa.Column('synthesis_model_id', sa.String(length=36), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('share_view_mode', sa.String(length=20), nullable=False),
    sa.Column('branch_naming_mode', sa.String(length=20), nullable=False),
    sa.Column('keybindings', sa.JSON(), nullable=True),
    sa.Column('highlight_color', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['default_model_id'], ['model_source_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['synthesis_model_id'], ['model_source_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('share_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_user_id'), 'share_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_user_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_branches_chat_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_nodes_parent_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_merge_parent_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_chat_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_model_source_models_source_id'), table_name='model_source_models')
    op.drop_table('model_source_models')
    op.drop_index(op.f('ix_model_sources_user_id'), table_name='model_sources')
    op.drop_table('model_sources')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('users')
    # ### end Alembic commands ###
